from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from geo_pipeline import DEFAULT_RESULTS_ROOT


METRICS = ("r2", "rmse", "mae")


def normalize_metric(values: np.ndarray, metric_name: str) -> np.ndarray:
    if np.allclose(values.max(), values.min()):
        return np.ones_like(values)
    if metric_name == "r2":
        return (values - values.min()) / (values.max() - values.min())
    return (values.max() - values) / (values.max() - values.min())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Plot radar charts from the saved metrics CSV.")
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_RESULTS_ROOT / "metrics" / "model_metrics.csv",
        help="Metrics CSV generated by the training script.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("figures") / "model_metrics_radar.png",
        help="Output PNG path.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)

    with args.input.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            grouped[row["target"]].append(row)

    if not grouped:
        raise SystemExit(f"No metric rows found in {args.input}")

    targets = list(grouped)
    fig, axes = plt.subplots(
        1,
        len(targets),
        figsize=(7 * len(targets), 6),
        subplot_kw={"polar": True},
    )
    axes_list = np.atleast_1d(axes)

    for axis, target in zip(axes_list, targets):
        rows = grouped[target]
        models = [row["model"] for row in rows]
        metric_matrix = np.asarray(
            [[float(row[metric_name]) for metric_name in METRICS] for row in rows],
            dtype=float,
        )

        normalized = np.column_stack(
            [normalize_metric(metric_matrix[:, index], metric_name) for index, metric_name in enumerate(METRICS)]
        )
        angles = np.linspace(0, 2 * np.pi, len(METRICS), endpoint=False).tolist()
        angles += angles[:1]

        for model_name, values in zip(models, normalized):
            closed_values = values.tolist() + [values[0]]
            axis.plot(angles, closed_values, linewidth=2, label=model_name)
            axis.fill(angles, closed_values, alpha=0.12)

        axis.set_thetagrids(np.degrees(angles[:-1]), [metric.upper() for metric in METRICS])
        axis.set_ylim(0, 1.05)
        axis.set_title(target)

    axes_list[-1].legend(loc="upper right", bbox_to_anchor=(1.35, 1.1))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(args.output, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Radar chart saved to: {args.output}")


if __name__ == "__main__":
    main()
